### PR TITLE
Prevent dead route

### LINKED ISSUE #505: This url (https://science.mozilla.org/programs) should be redirected
This url (https://science.mozilla.org/programs) should be redirected either into home page or into the event psge (https://science.mozilla.org/programs/events).

Now it showing a blank page.

### PR DESCRIPTION
**Pull request by alanmoo**
Closes #505. Thanks @amjadm61 for the heads up!

### CODE REVIEW

**Comment by gvn** [comment]
Could you not just do this?

https://github.com/alanmoo/science.mozilla.org/pull/1

**Comment by alanmoo** [comment]
@auremoser @acabunoc What do you think the right solution is here? Where should https://science.mozilla.org/programs direct users? It's not technically linked to from somewhere, but our URL structure might imply that it exists.

**Comment by acabunoc** [comment]
Redirecting to / makes sense to me - I think both your prs do that.

tbh https://github.com/alanmoo/science.mozilla.org/pull/1 makes sense to me

**Comment by auremoser** [comment]
Yeah, another page is just one more thing to maintain. I would redirect to home or whatever. When we have more than three programs we can make a landing page and replace it.

**Comment by alanmoo** [comment]
Hah, I wouldn't be opposed to that as an Easter egg  😁

**Comment by alanmoo** [comment]
@gvn take one more look at this?

**Comment by gvn** [comment]
👍

**Pull request merged**
