### PR TITLE
update fellows for 2017 bios and photos

### PR DESCRIPTION
**Pull request by auremoser**
Hi there, 
Just updating the fellows bios for 2017, in response to #654 .

I changed:
- the fellowships/fellows page, to add the two 2017 fellows
- added photos to the img/fellowships/ directory for each

Merge when you've deemed these changes acceptable please! Thank you!

cc/ @stephwright  @alanmoo

### CODE REVIEW

**Comment by auremoser** [comment]
Thanks @acabunoc . Merge when you'd like @alanmoo !

**Comment by auremoser** [comment]
Hey there! Noticed that this was merged but didn't populate on [the site](https://science.mozilla.org/programs/fellowships/fellows)...is there a staging step I should be aware of? Or another thing I need to do?

Thanks!

**Comment by acabunoc** [comment]
Looks like someone needs to push it to production via Heroku https://github.com/mozilla/science.mozilla.org#git-flow
 
flagging @alanmoo

**Comment by alanmoo** [comment]
Done, didn't want to deploy on a Friday

**Comment by stephwright** [comment]
Awww... thanks for looking out for us @alanmoo !

**Pull request merged**
