### PR TITLE
Remove fellows CTA

### LINKED ISSUE #532: Close fellows application
The Fellows application is now closed! 

Can we:
- [x] Hide the 'apply to be a fellow' hero images on the homepage
- [x] Hide the 'Apply Now' button on https://science.mozilla.org/programs/fellowships
- [x] Hide the 'Apply Now' block at the bottom of https://science.mozilla.org/programs/fellowships

### PR DESCRIPTION
**Pull request by alanmoo**
But make sprinkles still visible

Closes #532

### CODE REVIEW

**Comment by alicoding** [comment]
LGTM (code wise)

**Comment by alanmoo** [comment]
@acabunoc Check out the deployment to make sure it looks good? I removed the code, figuring if we need it back next year we can check the git history

**Comment by acabunoc** [comment]
Thanks @alanmoo!

Looks great - I ran this by @stephwright, instead of removing the bottom CTA, can we change it to "the 2016 call for applications is now closed"

Change this part:
screen shot 2016-07-19 at 12 10 45

Sorry I didn't think of this earlier!

**Comment by alanmoo** [comment]
Alright, that's been updated.

**Comment by acabunoc** [comment]
👍 thanks @alanmoo! 🌟

**Pull request merged**
