### PR TITLE
adding containers

### PR DESCRIPTION
**Pull request by gvn**
I erred on the side of more containers than might be needed, but I'll defer to design for how we should treat these sections. My general thought is that we might want to set a max width overall, but we'll see...

### CODE REVIEW

**Comment by alanmoo** [comment]
Not sure if this is new with this PR, but around 770px wide, the "What's New" section wraps oddly

**Comment by gvn** [comment]
Hmm, yeah I guess that's a regression here...

**Comment by gvn** [comment]
@alanmoo Ok, did some fixups

**Comment by alanmoo** [comment]
R+ once Travis is happy

**Pull request merged**
