### PR TITLE
adding CC to footer

### LINKED ISSUE #368: Add CC-BY 4.0 to the footer
This needs to present in the footer before we launch
https://creativecommons.org/licenses/by/4.0/

cc @kaythaney

### PR DESCRIPTION
**Pull request by gvn**
Closes #368

### CODE REVIEW

**Comment by alanmoo** [comment]
How hard is it to invert the SVG so it's dark/transparent letters on a light background?

**Comment by gvn** [comment]
Medium hard.

**Comment by alanmoo** [comment]
Code's fine then. If it needs to be inverted, maybe we can get some design assistance.

**Comment by gvn** [comment]
You're not just inverting it, you'd be changing the structure of the icon to not have a circular outline anymore, which feels off brand. I'll defer to design though...

**Pull request merged**
