### PR TITLE
Fixed Issue #580

### PR DESCRIPTION
**Pull request by dhiraj161298**
Fixed overflow of email bar in relatively smaller screen mobile devices.

### CODE REVIEW

**Comment by rahulkrishnan98** [comment]
Looks good to me. Thanks

**Comment by alanmoo** [comment]
What devices/screen sizes is this an issue on?

**Comment by dhiraj161298** [comment]
@alanmoo The issue @rahulkrishnan98 raised was for devices with viewport width less than 300px. There are few devices such as Samsung Wave S8500 and mini versions of some devices (not sure if they are around now) having viewport witdth 240px.

**Comment by alanmoo** [comment]
The issue with changing this to work for that case is that desktop browsers then get such a short field that some email addresses don't fit cleanly. I don't think it's worth that for a single 7 year old phone, which probably has a bunch of other rendering issues (if it can even render this site at all given its use of flexbox.) If you provide examples of a specific device in which this is an issue (meaning the rest of the site actually works), we can try and work with it but our general guideline is 320px wide is the minimum screen size supported.

**Pull request closed without merging**
