### PR TITLE
Button enhancement

### PR DESCRIPTION
**Pull request by dhiraj161298**
The two homepage button now animate on hover. The old look was pretty plain and inanimate.

### CODE REVIEW

**Comment by dhiraj161298** [comment]
@rahulkde Yes, I did. Travis failed as I missed a space between the property name and the opening parenthesis. I have got that fixed now.

**Comment by alanmoo** [comment]
Other than the need for a rebase off master to eliminate the duplicate commit, this is technically fine, and the right approach given our past code. However, could you investigate if it might be possible to use the `btn-outline` classes (described [here](https://v4-alpha.getbootstrap.com/components/buttons/#outline-buttons)) and get rid of the custom CSS for these buttons? You might need to override the colors for `btn-outline-secondary` or something, I'm not sure how easy that is given our current setup of importing MoFo-Bootstrap

**Comment by dhiraj161298** [comment]
@alanmoo Adding class btn-outline-secondary doesn't help much as almost all of the properties get overridden. What I found out was that the transition property added in this PR can actually be avoided.

**Comment by alanmoo** [comment]
Can you fix the merge conflicts on this? A rebase from master should do it.

**Pull request merged**
