### PR TITLE
sponsor block

### LINKED ISSUE #155: Homepage - Sponsor block

### PR DESCRIPTION
**Pull request by gvn**
I want to do a follow-on to replace the images with PNGs (hopefully w. transparency), but I need to get them from @kristinashu.

closes #155

### CODE REVIEW

**Comment by gvn** [comment]
Just realized, mobile is a bit different.

**Comment by kristinashu** [comment]
@gvn unfortunately the original logos are poor quality. Here they are as pngs but only one is transparent. 
logo-helmsley 2x
logo-sloan 2x

**Comment by gvn** [comment]
Ah, ok, in that case there's probably not going to be much of a improvement w. pngs.

**Comment by alanmoo** [comment]
This code is technically fine, but the layout gets a bit weird in the "small" breakpoint. I'd suggest moving the `col-sm` classes to `col-md`, but then you need some extra margins and it kind of spirals. So I guess R+ but will likely need some more work after a design review?

**Pull request merged**
