### PR TITLE
Event Study CTA and What's New - padding

### PR DESCRIPTION
**Pull request by amjadm61**

### CODE REVIEW

**Comment by alanmoo** [comment]
There's a few things going on here:

* The PR has landed to fix the size of the "What's New" heading, so you need to rebase off develop to resolve conflicts
* Checks have failed- run `npm test` locally to see what's going on
* You can resolve the padding issues by using the bootstrap utility classes linked to in the (updated) readme, you shouldn't need more CSS. Something like `p-y-2` instead of a new className should solve it.

**Comment by amjadm61** [comment]
@alanmoo thanks for the feedback.
Pls have a look on the new commits and looking for your feedback. Then I can try to make my future code more perfectly.

**Comment by alanmoo** [comment]
You're getting closer. Keep in mind that there are only utility classes with integers 0-3, so a decimal in the className won't do anything. Also, it will help to discard your changes in the .scss file so that you can rebase properly from the develop branch (that will make the "This branch has conflicts that must be resolved" message below go away.

**Comment by amjadm61** [comment]
@alanmoo I've updated the utility classes by using integers only, but the branch conflict error message "This branch has conflicts that must be resolved"  still there.

**Comment by alanmoo** [comment]
If you rebase off the develop branch that should go away. You could probably also get it to go away by reverting home.scss to the way it originally was- remove the extra space at the start of line 96 and add `font-weight: 100` back to line 105.

**Comment by amjadm61** [comment]
I've opened a new pull request #498 for this because of the branch conflict error issue.

So, I'm closing this.

**Pull request closed without merging**
