### PR TITLE
Enable applying for fellowships

### PR DESCRIPTION
**Pull request by gideonthomas**
Enables the Fellowships application

### CODE REVIEW

**Comment by acabunoc** [comment]
one last 'apply now' hidden at the bottom:
https://github.com/gideonthomas/science.mozilla.org/blob/19600f42a465731e154d1d27301354630a7e1af8/app/react/pages/fellowships/fellowships.jsx#L203

**Comment by acabunoc** [comment]
...aaaand on the home page:
https://github.com/mozilla/science.mozilla.org/blob/develop/app/react/pages/home/home.jsx#L27

**Comment by gideonthomas** [comment]
fixing

**Comment by alanmoo** [comment]
Thanks, Gideon!

**Comment by gvn** [comment]
👍

**Pull request merged**
