### PR TITLE
adding filter to Resources

### LINKED ISSUE #366: Add sorting filter to Resources view

### PR DESCRIPTION
**Pull request by gvn**
Closes #366

### CODE REVIEW

**Comment by alanmoo** [comment]
This looks good, but make the titles of the cards links (using the key in the data for each card) with a class of `project-name m-y-1`

**Comment by gvn** [comment]
Ok, did that fixup.

**Comment by alanmoo** [comment]
Travis failed

**Comment by gvn** [comment]
Not sure why Travis is failing. I ran it on a PR that passed earlier, and it failed. I'm gonna have to figure that out later, but for now this is passing `npm test` locally...

**Comment by alanmoo** [comment]
This inspired https://github.com/mozilla/science.mozilla.org/issues/373

**Pull request merged**
