### PR TITLE
Project filtering by category

### LINKED ISSUE #158: Projects main page API integration
Including searching/filtering

When searching and then opening a project link, navigating back to the main page should show the same search filters/results.

### PR DESCRIPTION
**Pull request by alanmoo**
This can be DRYer, need to add API library soon. Closes #158 though.

### CODE REVIEW

**Comment by alanmoo** [comment]
Uh, Travis why are you being difficult?

**Comment by alicoding** [comment]
r+ with travis green

**Comment by alanmoo** [comment]
I have no idea why Travis is failing though. Something about node-sass...

**Comment by alicoding** [comment]
I just had to rebuild travis build

**Comment by alanmoo** [comment]
Thanks, I'd tried ammending a comment with a force push last night and it rebuilt yet failed again

**Pull request merged**
