### PR TITLE
Less bad blog styles

### PR DESCRIPTION
**Pull request by alanmoo**
Starts to address #536

### CODE REVIEW

**Comment by alanmoo** [comment]
(Working on addressing the stylelint errors)

**Comment by sabrinang** [comment]
Design feedback:
science-blog_design-feedback

**Comment by alanmoo** [comment]
@sabrinang I've:

* Made the font 'Fira Sans' again
* Made H1 (blog entry title) bigger and not bold
* Equalized the space above and below the entry tags
* Added some space above the image

I haven't:

* Centered the caption- this is how it renders in the wordpress editor and the goal of this change was to make it easier to understand what the post will look like
* Changed the rest of the font sizes- same as above reasoning
* Changed the caption padding- I'm not sure why you see no padding there, perhaps you need to hard refresh, as I have padding.

**Comment by sabrinang** [comment]
Thanks for making the updates @alanmoo R+ definitely less bad blog styles :+1:

**Pull request merged**
