### PR TITLE
global sprint map add

### PR DESCRIPTION
**Pull request by auremoser**
Hi @acabunoc, ready for review, I added the site map and we can edit the [data here](https://auremoser.cartodb.com/viz/ed575994-f063-11e5-a94e-0e3ff518bd15/public_map).

Screenshot:
gsprint

### CODE REVIEW

**Comment by acabunoc** [comment]
Thanks @auremoser! links in the embedded map aren't work for me -- also I can't seem to edit the data

**Comment by auremoser** [comment]
Hmm, I target="blank"'d the links so they should work onclick.
gs

The datasets are downloadable from the cartodb site, both the [timezone layer](https://auremoser.cartodb.com/tables/ne_10m_time_zones/public) and the [global sprint site data](https://auremoser.cartodb.com/tables/table_sheet1/public).

Hope that helps @acabunoc , you can export them as geojson or just do the api call.

**Comment by auremoser** [comment]
Here is an example of it working in the local embed version:
embed

**Comment by acabunoc** [comment]
Oh thanks! The target=_blank seems to have fixed it all :) And I can see the datasets now! yay

I'll work on getting this + list of sites live today (lotsa down time while I watch this datathon go on 😜). Any way @arlissc & I can edit the dataset? I think there are a couple sites that aren't ready for registrants yet.

**Comment by auremoser** [comment]
Yeah weirdly there's only a way I can make the datasets public, but
collaborating on it requires you to login to my account. I'll email you the
details.

Aurelia

On Sat, Apr 30, 2016 at 11:52 AM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> Oh thanks! The target=_blank seems to have fixed it all :) And I can see
> the datasets now! yay
>
> I'll work on getting this + list of sites live today (lotsa down time
> while I watch this datathon go on 😜). Any way @arlissc
> <https://github.com/arlissc> & I can edit the dataset? I think there are
> a couple sites that aren't ready for registrants yet.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/science.mozilla.org/pull/268#issuecomment-215974757>
>



-- 
Aurelia Moser
Community Lead, Mozilla Science Lab
Twitter @auremoser | GitHub @auremoser | Skype: auremoser1

**Comment by acabunoc** [comment]
weird! Thanks @auremoser :) Safe travels, hope your Berlin prep is going well!

**Pull request merged**
